services:
  grafana:
    image: grafana/grafana-oss
    restart: always
    ports:
      - 3000:3000
    volumes:
      - grafana-storage:/var/lib/grafana
  graphite:
    image: graphiteapp/graphite-statsd
    restart: always
    ports:
      - 8080:80
      - 2003-2004:2003-2004
      - 2023-2024:2023-2024
      - 8125:8125/udp
      - 8126:8126
  prometheus:
    image: prom/prometheus
    restart: always
    network_mode: host
    volumes:
      - "./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
      - "./prometheus/targets:/etc/prometheus/targets"
    ports:
      - 9090:9090
  prm-exp-prusa:
    build:
      context: prometheus/exporters/prusa
      dockerfile: prometheus/exporters/prusa/prusa.dockerfile
    restart: always
  # glances:
  #   build: ./glances
  #   restart: always
  #   environment:
  #     - GLANCES_OPT=--export graphite
  #   ports:
  #     - 61208-61209:61208-61209
volumes:
  grafana-storage:
