version: '3'
services:
  grafana:
    image: grafana/grafana-oss
    ports:
      - 3000:3000
    volumes:
      - grafana-storage:/var/lib/grafana
  graphite:
    image: graphiteapp/graphite-statsd
    ports:
      - 8080:80
      - 2003-2004:2003-2004
      - 2023-2024:2023-2024
      - 8125:8125/udp
      - 8126:8126
volumes:
  grafana-storage:
