global:
  scrape_interval: 10s

scrape_configs:
  # Self-Monitoring
  - job_name: prometheus
    static_configs:
      - targets:
          - prometheus:9090

  # Sensors
  - job_name: "sensors"
    file_sd_configs:
      - files: ["/etc/prometheus/targets/sensors/*.yml"]

  # Prusa 3D Printers
  - job_name: "prusa-mini-1"
    metrics_path: /metrics/prusa-mini-1
    file_sd_configs:
      - files: ["/etc/prometheus/targets/prusa/prusa-mini-1.yml"]

  - job_name: "prusa-mk4-1"
    metrics_path: /metrics/prusa-mk4-1
    file_sd_configs:
      - files: ["/etc/prometheus/targets/prusa/prusa-mk4-1.yml"]
